### ISSUE TITLE
No WSL (Windows Subsystem for Linux) support?

### ISSUE THREAD

**Issue by robinhood2014** [alexmurray/shortwave-snap#10]
Trying to install Shortwave in a Windows Subsystem for Linux (WSL) environment. `sudo snap install shortwave` apparently works correctly, but when I try running it, it doesn't work at all.

1. Launching Shortwave from the Windows Start menu -> nothing happens whatsoever.
2. Going to the terminal and typing in `shortwave` -> I get this:
```
2023/12/01 10:19:34.877157 cmd_run.go:1055: WARNING: cannot start document portal: dial unix /run/user/1000/bus: connect: no such file or directory

(shortwave:2651): Gtk-WARNING **: 10:19:35.040: Unable to acquire session bus: Could not connect: No such file or directory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Failed to connect to socket /run/user/1000/bus: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)', /build/shortwave/parts/shortwave/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/mpris-player-0.6.2/src/mpris_player.rs:78:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
3. `RUST_BACKTRACE=1 shortwave` yields this in addition:
```
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ujz1Py/rustc-1.66.1+dfsg0ubuntu1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /build/rustc-ujz1Py/rustc-1.66.1+dfsg0ubuntu1/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /build/rustc-ujz1Py/rustc-1.66.1+dfsg0ubuntu1/library/core/src/result.rs:1791:5
   3: mpris_player::mpris_player::MprisPlayer::new
   4: shortwave::audio::controller::mpris_controller::MprisController::new
   5: glib::subclass::types::ObjectSubclass::with_class
   6: glib::subclass::types::instance_init
   7: g_type_create_instance
   8: <unknown>
   9: g_object_newv
  10: glib::object::Object::new_internal
  11: glib::object::Object::with_type
  12: glib::object::Object::new
  13: shortwave::app::SwApplication::run
  14: shortwave::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
4. `RUST_BACKTRACE=full shortwave` -> output in the attached text file.
[traceback.txt](https://github.com/alexmurray/shortwave-snap/files/13529935/traceback.txt)

My first impression is that this might just be a WSL problem; i.e. it simply doesn't like this particular program; in which case I may as well be talking to a brick wall here. But on the slightest, against-all-odds chance this can be fixed, I'd appreciate whatever help you can give.

**Comment by alexmurray** [comment]
Can you please try with the latest version of the snap? Thanks.
